/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/
package staticdata
{
	import flash.utils.ByteArray;
	import staticdata.define.*

	public class Reward extends StaticInfoBase
	{
		public var id:int;		//id
		public var name:String;		//物品名称
		public var probability:int;		//可能奖励出现概率（千分比）
		public var min:int;		//可能奖励最小数量
		public var max:int;		//可能奖励最大数量
		public var activity:Array;		//受活动控制id
		public var rewardCertain:Vector.<Certain>;	
		public var rewardMaybe:Vector.<Maybe>;	

		public function Reward(data:ByteArray)
		{
			super(data);
			id = data.readInt();
			name = data.readUTF();
			rewardCertain = new Vector.<Certain>();
			var l:int = data.readUnsignedByte();
			for(var i:int = 0; i < l; i++)
			{
				var eachCertain : Certain = new Certain();
				eachCertain.certainType = data.readInt();
				eachCertain.certainId = data.readInt();
				eachCertain.certainValue = data.readInt();

				rewardCertain.push(eachCertain);
			}

			rewardMaybe = new Vector.<Maybe>();
			var l:int = data.readUnsignedByte();
			for(i = 0; i < l; i++)
			{
				var eachMaybe : Maybe = new Maybe();
				eachMaybe.maybeType = data.readInt();
				eachMaybe.maybeId = data.readInt();
				eachMaybe.maybeValue = data.readInt();
				eachMaybe.maybeProbability = data.readInt();

				rewardMaybe.push(eachMaybe);
			}

			probability = data.readUnsignedShort();
			min = data.readUnsignedByte();
			max = data.readUnsignedByte();
			activity = data.readUTF().split("_");		
		}
	}
}
