/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/
package staticdata
{
	import flash.utils.ByteArray;
	import staticdata.define.*

	public class SceneLimit extends StaticInfoBase
	{
		public var id:int;		//ID
		public var areaId:int;		//区域限制id
		public var limitAreaType:int;		//场景进入限制//限制类型_限制数据1等级限制_等级2任务限制_任务id3杀怪_怪物id0
		public var limitAreaData:int;		//场景进入限制//限制类型_限制数据1等级限制_等级2任务限制_任务id3杀怪_怪物id0

		public function SceneLimit(data:ByteArray)
		{
			super(data);
			id = data.readInt();
			areaId = data.readInt();
			limitAreaType = data.readUnsignedByte();
			limitAreaData = data.readInt();		
		}
	}
}
