/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/
package staticdata
{
	import flash.utils.ByteArray;
	import staticdata.define.*

	public class Scene extends StaticInfoBase
	{
		public var id:int;		//ID
		public var name:String;		//地图名称
		public var file:String;		//文件名
		public var type:int;		//场景类型1大地图（后端实时坐标）2城镇&野外地图（无需实时地图）3战斗地图（全3D）4活动地图
		public var limitType:int;		//场景进入限制//限制类型_限制数据1等级限制_等级2任务限制_任务id3杀怪_怪物id0
		public var limitData:int;		//场景进入限制//限制类型_限制数据1等级限制_等级2任务限制_任务id3杀怪_怪物id0
		public var horseLimit:int;		//场景特殊类型主要限制坐骑1天空2海洋0无特殊能力
		public var limitAreaInto:Array;		//区域限制条件子表ID
		public var coordinatesX:int;		//地图出生点//X坐标_Y坐标
		public var coordinatesY:int;		//地图出生点//X坐标_Y坐标
		public var musicId:Array;		//音乐子表id
		public var createType:int;		//创建方式:0 预设创建1 动态创建(组队副本，攻城战)
		public var waypointId:Array;		//通道表id

		public function Scene(data:ByteArray)
		{
			super(data);
			id = data.readInt();
			name = data.readUTF();
			file = data.readUTF();
			type = data.readUnsignedByte();
			limitType = data.readUnsignedByte();
			limitData = data.readInt();
			horseLimit = data.readUnsignedByte();
			limitAreaInto = data.readUTF().split("_");
			coordinatesX = data.readUnsignedShort();
			coordinatesY = data.readUnsignedShort();
			musicId = data.readUTF().split("_");
			createType = data.readUnsignedByte();
			waypointId = data.readUTF().split("_");		
		}
	}
}
