/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/
package staticdata
{
	import flash.utils.ByteArray;
	import staticdata.define.*

	public class SceneWayPoint extends StaticInfoBase
	{
		public var id:int;		//ID
		public var fromMapId:int;		////场景id_X坐标_Y坐标
		public var fromX:int;		////场景id_X坐标_Y坐标
		public var fromY:int;		////场景id_X坐标_Y坐标
		public var toMapId:int;		////场景id_X坐标_Y坐标
		public var toX:int;		////场景id_X坐标_Y坐标
		public var toY:int;		////场景id_X坐标_Y坐标
		public var radius:int;		//半径

		public function SceneWayPoint(data:ByteArray)
		{
			super(data);
			id = data.readInt();
			fromMapId = data.readInt();
			fromX = data.readUnsignedShort();
			fromY = data.readUnsignedShort();
			toMapId = data.readInt();
			toX = data.readUnsignedShort();
			toY = data.readUnsignedShort();
			radius = data.readUnsignedByte();		
		}
	}
}
