/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/
package staticdata
{
	import flash.utils.ByteArray;
	import staticdata.define.*

	public class SceneMusic extends StaticInfoBase
	{
		public var id:int;		//ID
		public var type:int;		//音乐类型1音乐2音效
		public var limitType:int;		//限定范围1场景2场景区域
		public var limitId:int;		//场景&区域id
		public var file:int;		//音乐文件名

		public function SceneMusic(data:ByteArray)
		{
			super(data);
			id = data.readInt();
			type = data.readUnsignedByte();
			limitType = data.readUnsignedByte();
			limitId = data.readInt();
			file = data.readInt();		
		}
	}
}
