/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/
package staticdata
{
	import flash.utils.ByteArray;
	import staticdata.define.*

	public class SceneArea extends StaticInfoBase
	{
		public var id:int;		//ID
		public var sceneId:int;		//场景总表id
		public var coordinatesX:int;		//中心坐标//X坐标_Y坐标
		public var coordinatesY:int;		//中心坐标//X坐标_Y坐标
		public var type:int;		//图形类型//图像类型_图形数据_图形数据1圆形_角度_半径(角度以地图长为x轴，逆时针旋转)2矩形_长_宽
		public var dataA:int;		//图形类型//图像类型_图形数据_图形数据1圆形_角度_半径(角度以地图长为x轴，逆时针旋转)2矩形_长_宽
		public var dataB:int;		//图形类型//图像类型_图形数据_图形数据1圆形_角度_半径(角度以地图长为x轴，逆时针旋转)2矩形_长_宽

		public function SceneArea(data:ByteArray)
		{
			super(data);
			id = data.readInt();
			sceneId = data.readInt();
			coordinatesX = data.readUnsignedShort();
			coordinatesY = data.readUnsignedShort();
			type = data.readUnsignedByte();
			dataA = data.readUnsignedShort();
			dataB = data.readUnsignedShort();		
		}
	}
}
