/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/
package staticdata
{
	import flash.utils.ByteArray;
	import staticdata.define.*

	public class SkillArt extends StaticInfoBase
	{

		public function SkillArt(data:ByteArray)
		{
			super(data);		
		}
	}
}
