/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/
package staticdata
{
	import flash.utils.ByteArray;
	import staticdata.define.*

	public class SkillBallistic extends StaticInfoBase
	{
		public var id:int;		//id
		public var type:int;		//弹道类型1轨迹型弹道2持续连线型弹道/持续时间为buff时间或从发射到伤害核算结束时间/3原点（目标）变化弹道4xx
		public var xycoordinateAngle:int;		//xy坐标角度人物垂直于地面为0度逆时针旋转最大区间为360
		public var trackType:int;		//弹道轨迹分类1直线弹道（攻击与目标连线）2轨迹弹道（填写配置id）3环形弹道（逆时针旋转）4XX
		public var trackId:int;		//弹道轨迹配置文件
		public var radius:int;		//环形弹道半径（格子为单位）
		public var speed:int;		//初始速度多少格1秒
		public var endAngle:int;		//停滞角度相对于X轴逆时针角度正方向为0-90&270-360(只有环形弹道需要填写)
		public var trackTime:int;		//弹道飞行轨迹时间(毫秒)
		public var collision:int;		//弹道是否发生碰撞1碰撞消失2碰撞穿透0不碰撞

		public function SkillBallistic(data:ByteArray)
		{
			super(data);
			id = data.readInt();
			type = data.readUnsignedByte();
			xycoordinateAngle = data.readInt();
			trackType = data.readUnsignedByte();
			trackId = data.readInt();
			radius = data.readInt();
			speed = data.readInt();
			endAngle = data.readInt();
			trackTime = data.readInt();
			collision = data.readUnsignedByte();		
		}
	}
}
