/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/
package staticdata
{
	import flash.utils.ByteArray;
	import staticdata.define.*

	public class SkillBuff extends StaticInfoBase
	{
		public var id:int;		//id
		public var name:String;		//buff名称
		public var type:int;		//buff类型1buff2debuff3治疗型buff4伤害型debuff5永久buff（12类型持续时间后还原buff前属性，34类型buff消失不影响现有属性）
		public var continuousTime:int;		//持续总时间（毫秒，1000毫秒=1秒）/永久buff 填写0 /
		public var freguency:int;		//34类型数值触发频率
		public var effect:int;		//BUFF效果0无1眩晕2沉默3魅惑4吸血5共摊伤害
		public var effectControl:int;		//buff效果是否控制计算1是0否
		public var caculateType:int;		//计算模式0无需计算1根据本身的基础数值计算2根据公式数值计算3根据收到的技能伤害比例计算
		public var basic:int;		//直接叠加数数值型别1血量上限2当前血量3攻击强度4防御值5XXX0无
		public var basicPermil:int;		//叠加数值（公式系数&千分比）
		public var growControl:Array;		//成长系数控制值1叠加属性2持续时间3xx
		public var growCoefficient:int;		//成长系数(千分比&毫秒)
		public var caculator:int;		//计数器投放1受击打计数2标记者扣血数值0无计数器

		public function SkillBuff(data:ByteArray)
		{
			super(data);
			id = data.readInt();
			name = data.readUTF();
			type = data.readUnsignedByte();
			continuousTime = data.readInt();
			freguency = data.readUnsignedByte();
			effect = data.readUnsignedByte();
			effectControl = data.readUnsignedByte();
			caculateType = data.readUnsignedByte();
			basic = data.readUnsignedByte();
			basicPermil = data.readInt();
			growControl = data.readUTF().split("_");
			growCoefficient = data.readInt();
			caculator = data.readUnsignedByte();		
		}
	}
}
