/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/
package protobuf
{
	import flash.utils.Dictionary;
	import protobuf.battle.battle_pve_in;
	import protobuf.battle.battle_pve_in_r;
	import protobuf.battle.notify_battle_pve_end_r;
	import protobuf.battle.use_anger;
	import protobuf.battle.notify_battle_init_data_r;
	import protobuf.battle.notify_battle_event_r;
	import protobuf.chat.chat;
	import protobuf.chat.chat_r;
	import protobuf.login.login;
	import protobuf.login.login_norole_r;
	import protobuf.login.login_role_r;
	import protobuf.login.create_role;
	import protobuf.login.get_rand_nick;
	import protobuf.login.get_rand_nick_r;
	import protobuf.mail.mail_read;
	import protobuf.mail.mail_read_r;
	import protobuf.mail.mail_attachment;
	import protobuf.mail.mail_attachment_r;
	import protobuf.mail.notify_mail_r;
	import protobuf.mixture.rank_list;
	import protobuf.mixture.rank_list_r;
	import protobuf.scene.enter_map;
	import protobuf.scene.enter_map_r;
	import protobuf.scene.move;
	import protobuf.scene.move_r;
	import protobuf.scene.notify_map_out_r;
	import protobuf.scene.notify_map_in_r;
	import protobuf.share.err_r;
	import protobuf.share.heartbeat;
	import protobuf.share.heartbeat_r;
	import protobuf.shop.get_ad;
	import protobuf.shop.get_ad_r;
	import protobuf.shop.get_record;
	import protobuf.shop.get_record_r;
	import protobuf.shop.buy_goods;
	import protobuf.shop.buy_goods_r;
	public class MessageMap
	{
		public static var SCMap:Dictionary = new Dictionary();
		public static var CSMap:Dictionary = new Dictionary();

		SCMap[0x0901] = battle_pve_in_r;
		SCMap[0x0902] = notify_battle_pve_end_r;
		SCMap[0x0a00] = notify_battle_init_data_r;
		SCMap[0x0a01] = notify_battle_event_r;
		SCMap[0x0300] = chat_r;
		SCMap[0x01f2] = login_norole_r;
		SCMap[0x01f3] = login_role_r;
		SCMap[0x01f5] = get_rand_nick_r;
		SCMap[0x0501] = mail_read_r;
		SCMap[0x0502] = mail_attachment_r;
		SCMap[0x0503] = notify_mail_r;
		SCMap[0x0403] = rank_list_r;
		SCMap[0x0201] = enter_map_r;
		SCMap[0x0202] = move_r;
		SCMap[0x0203] = notify_map_out_r;
		SCMap[0x0204] = notify_map_in_r;
		SCMap[0x0001] = err_r;
		SCMap[0x0002] = heartbeat_r;
		SCMap[0x0600] = get_ad_r;
		SCMap[0x601] = get_record_r;
		SCMap[0x602] = buy_goods_r;

		CSMap[battle_pve_in] = 0x0901;
		CSMap[use_anger] = 0x0903;
		CSMap[chat] = 0x0300;
		CSMap[login] = 0x01f1;
		CSMap[create_role] = 0x01f4;
		CSMap[get_rand_nick] = 0x01f5;
		CSMap[mail_read] = 0x0501;
		CSMap[mail_attachment] = 0x0502;
		CSMap[rank_list] = 0x0403 ;
		CSMap[enter_map] = 0x0201;
		CSMap[move] = 0x0202;
		CSMap[heartbeat] = 0x0002;
		CSMap[get_ad] = 0x0600;
		CSMap[get_record] = 0x601;
		CSMap[buy_goods] = 0x602;
	}
}