/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/
package staticdata.define
{
	public class Certain
	{
		public var certainType:int;
		public var certainId:int;
		public var certainValue:int;

		public function Certain(certainType:int = 0, certainId:int = 0, certainValue:int = 0)
		{
			this.certainType = certainType;
			this.certainId = certainId;
			this.certainValue = certainValue;
		}
	}
}

