/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/
package staticdata.define
{
	public class ChannelType
	{
		public var mapId:int;
		public var x:int;
		public var y:int;

		public function ChannelType(mapId:int = 0, x:int = 0, y:int = 0)
		{
			this.mapId = mapId;
			this.x = x;
			this.y = y;
		}
	}
}

