/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/
package staticdata.define
{
	public class Maybe
	{
		public var maybeType:int;
		public var maybeId:int;
		public var maybeValue:int;
		public var maybeProbability:int;

		public function Maybe(maybeType:int = 0, maybeId:int = 0, maybeValue:int = 0, maybeProbability:int = 0)
		{
			this.maybeType = maybeType;
			this.maybeId = maybeId;
			this.maybeValue = maybeValue;
			this.maybeProbability = maybeProbability;
		}
	}
}

