/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/

#pragma once

#include <lib_file_tab_txt.h>
#include <lib_util.h>

namespace scene_area_auto{

	struct scene_area_cfg_t
	{
		uint32_t id;		//ID	
		uint32_t scene_id;		//场景总表id	
		uint16_t coordinates_x;		//中心坐标//X坐标_Y坐标	
		uint16_t coordinates_y;		//中心坐标//X坐标_Y坐标	
		uint8_t type;		//图形类型//图像类型_图形数据_图形数据1圆形_角度_半径(角度以地图长为x轴，逆时针旋转)2矩形_长_宽	
		uint16_t data_a;		//图形类型//图像类型_图形数据_图形数据1圆形_角度_半径(角度以地图长为x轴，逆时针旋转)2矩形_长_宽	
		uint16_t data_b;		//图形类型//图像类型_图形数据_图形数据1圆形_角度_半径(角度以地图长为x轴，逆时针旋转)2矩形_长_宽	

		void load(el::lib_file_tab_txt_t& file_tab_txt, std::vector<std::string>& ref){
			std::string __str_def__;

			this->id= file_tab_txt.get_val_def("id", ref, 0);
			this->scene_id= file_tab_txt.get_val_def("scene_id", ref, 0);
			this->coordinates_x= file_tab_txt.get_val_def("coordinates_x", ref, 0);
			this->coordinates_y= file_tab_txt.get_val_def("coordinates_y", ref, 0);
			this->type= file_tab_txt.get_val_def("type", ref, 0);
			this->data_a= file_tab_txt.get_val_def("data_a", ref, 0);
			this->data_b= file_tab_txt.get_val_def("data_b", ref, 0);		
		}
	};
}
