/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/

#pragma once

#include <lib_file_tab_txt.h>
#include <lib_util.h>

namespace scene_music_auto{

	struct scene_music_cfg_t
	{
		uint32_t id;		//ID	
		uint8_t type;		//音乐类型1音乐2音效	
		uint8_t limit_type;		//限定范围1场景2场景区域	
		uint32_t limit_id;		//场景&区域id	
		uint32_t file;		//音乐文件名	

		void load(el::lib_file_tab_txt_t& file_tab_txt, std::vector<std::string>& ref){
			std::string __str_def__;

			this->id= file_tab_txt.get_val_def("id", ref, 0);
			this->type= file_tab_txt.get_val_def("type", ref, 0);
			this->limit_type= file_tab_txt.get_val_def("limit_type", ref, 0);
			this->limit_id= file_tab_txt.get_val_def("limit_id", ref, 0);
			this->file= file_tab_txt.get_val_def("file", ref, 0);		
		}
	};
}
