/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/

#pragma once

#include <lib_file_tab_txt.h>
#include <lib_util.h>

namespace scene_limit_auto{

	struct scene_limit_cfg_t
	{
		uint32_t id;		//ID	
		uint32_t area_id;		//区域限制id	
		uint8_t limit_area_type;		//场景进入限制//限制类型_限制数据1等级限制_等级2任务限制_任务id3杀怪_怪物id0	
		uint32_t limit_area_data;		//场景进入限制//限制类型_限制数据1等级限制_等级2任务限制_任务id3杀怪_怪物id0	

		void load(el::lib_file_tab_txt_t& file_tab_txt, std::vector<std::string>& ref){
			std::string __str_def__;

			this->id= file_tab_txt.get_val_def("id", ref, 0);
			this->area_id= file_tab_txt.get_val_def("area_id", ref, 0);
			this->limit_area_type= file_tab_txt.get_val_def("limit_area_type", ref, 0);
			this->limit_area_data= file_tab_txt.get_val_def("limit_area_data", ref, 0);		
		}
	};
}
