/*
*
* Copyright 2016
* All rights reserved.
* This file is automatically generated by python script of which 
* the author is wupeng.
*
*/

#pragma once

#include <lib_file_tab_txt.h>
#include <lib_util.h>

namespace scene_way_point_auto{

	struct scene_way_point_cfg_t
	{
		uint32_t id;		//ID	
		uint32_t from_map_id;		////场景id_X坐标_Y坐标	
		uint16_t from_x;		////场景id_X坐标_Y坐标	
		uint16_t from_y;		////场景id_X坐标_Y坐标	
		uint32_t to_map_id;		////场景id_X坐标_Y坐标	
		uint16_t to_x;		////场景id_X坐标_Y坐标	
		uint16_t to_y;		////场景id_X坐标_Y坐标	
		uint8_t radius;		//半径	

		void load(el::lib_file_tab_txt_t& file_tab_txt, std::vector<std::string>& ref){
			std::string __str_def__;

			this->id= file_tab_txt.get_val_def("id", ref, 0);
			this->from_map_id= file_tab_txt.get_val_def("from_map_id", ref, 0);
			this->from_x= file_tab_txt.get_val_def("from_x", ref, 0);
			this->from_y= file_tab_txt.get_val_def("from_y", ref, 0);
			this->to_map_id= file_tab_txt.get_val_def("to_map_id", ref, 0);
			this->to_x= file_tab_txt.get_val_def("to_x", ref, 0);
			this->to_y= file_tab_txt.get_val_def("to_y", ref, 0);
			this->radius= file_tab_txt.get_val_def("radius", ref, 0);		
		}
	};
}
